# Whether files should be placed in a directory named after the server they have been pulled from.
use-server-name-directories = true

# Number of concurrent HTTP Requests to make
concurrent-requests = 5

# A list of server names mapped to a URL containing a valid RSS/Atom feed
[servers]
"Plato Releases" = { url = "https://github.com/baskerville/plato/releases.atom" }
